version: 2.1
orbs:
  docker: circleci/docker@1.0.0
jobs:
  run_tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
  deploy_image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: jithinktom/react-brushup
      - docker/push:
          digest-path: /tmp/digest.txt
          image: jithinktom/react-brushup
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  build_and_deploy:
    jobs:
      - run_tests
      - deploy_image:
          requires:
            - run_tests
