version: 2.1
orbs:
  docker: circleci/docker@1.0.0
jobs:
  run_tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:latest
    steps: 
      run: docker build . -t jithinktom/react-brushup
workflows:
  build_and_deploy:
    jobs:
      - run_tests
      - deploy:
          requires:
            - run_tests
      # - docker/publish:
      #     path: 
      #     image: jithinktom/react-brushup
      #     dockerfile: dockerfile
      #     requires:
      #       - run_tests
      #     filters:
      #       branches:
      #         only: 
      #           - master