version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  run_tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  
workflows:
  build_deploy:
    jobs:
      - run_tests
      - docker/publish:
          image: jithinktom/react-brushup
          dockerfile: dockerfile
          requires:
            - run_tests
          filters:
            branches:
              only: 
                - master